default: &default
  adapter: "redis"
  url: "<%= ENV.fetch("REDIS_URL") { "redis://redis:6379/1" } %>"

development:
  <<: *default
  channel_prefix: "ppay_app_development"
  url: "redis://localhost:6379/1"

test:
  <<: *default
  adapter: "test"

production:
  <<: *default
  channel_prefix: "ppay_app_production"

