default: &default
  adapter: "redis"
  url: url: "<%= "redis://#{ ENV['REDIS_HOST'] || 'redis' }:6379" %>"

development:
  <<: *default
  channel_prefix: "ppay_app_development"
  url: url: "<%= "redis://#{ ENV['REDIS_HOST'] || 'redis' }:6379" %>"

test:
  <<: *default
  adapter: "test"

production:
  <<: *default
  channel_prefix: "ppay_app_production"

