default: &default
  adapter: postgresql
  encoding: "unicode"
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: "ppay_app_test"

test:
  <<: *default
  database: "ppay_app_test"

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "ppay" } %>_production
  username: "<%= ENV.fetch("POSTGRES_USER") { "postgres" } %>"
  password: "<%= ENV.fetch("POSTGRES_PASSWORD") { "hello_password" } %>"
  host: "<%= ENV.fetch("POSTGRES_HOST") { "postgres" } %>"
  port: "<%= ENV.fetch("POSTGRES_PORT") { 5432 } %>"
  # http://guides.rubyonrails.org/configuring.html#database-pooling

