basic_auth:
  username: ppay
  password: password

external_callback_path: api/v1/external_processing/payments/bnn_update_callback

simbank_nickname: Симбанк

navbar:
  super_admin:
    - name: Оборот
      path: turnover_stats_path
    - name: Балансы
      path: balances_path
    - name: Запросы баланса
      path: balance_requests_path
  admin:
    - name: Все платежи
      path: payments_path
    - name: Объявления
      path: advertisements_path
    - name: Запросы баланса
      path: balance_requests_path
    - name: Телеграм Бот
      path: edit_admins_profile_path
    - name: Мерчанты
      path: merchants_path
    - name: Операторы
      path: processers_path
    - name: Настройки
      path: edit_setting_path
    - name: Регулярки
      path: masks_path
    - name: Реестр платежей
      path: incoming_requests_path
    - name: Оборот
      path: turnover_stats_path
    - name: Реестр ненайденных платежей
      path: not_found_payments_path
    - name: Платёжные системы
      path: payment_systems_path
    - name: Статистика
      path: dashboard_path
    - name: Телеграм приложения
      path: telegram_applications_path
    - name: Телеграм боты
      path: telegram_bots_path
  merchant:
    - name: Все платежи
      path: payments_path
    - name: Создать оплату
      path: new_payments_deposit_path
    - name: Запросы баланса
      path: balance_requests_path
    - name: Телеграм Бот
      path: edit_merchants_profile_path
    - name: Арбитражи по чеку
      path: arbitrations_path
    - name: Замороженные средства
      path: transactions_path
  processer:
    - name: Все платежи
      path: payments_path
    - name: Объявления
      path: advertisements_path
    - name: Курсы бирж
      path: rate_snapshots_path
    - name: Запросы баланса
      path: balance_requests_path
    - name: Телеграм Бот
      path: edit_processers_profile_path
    - name: Обработка
      path: flow_advertisements_path
    - name: Арбитражи по чеку
      path: arbitrations_path
    - name: Статистика
      path: dashboard_path
    - name: Реестр платежей
      path: incoming_requests_path
  support:
    - name: Все платежи
      path: payments_path
    - name: Объявления
      path: advertisements_path
    - name: Запросы баланса
      path: balance_requests_path
    - name: Телеграм Бот
      path: edit_supports_profile_path
    - name: Реестр ненайденных платежей
      path: not_found_payments_path
    - name: Арбитражи по чеку
      path: arbitrations_path
    - name: Статистика
      path: dashboard_path
    - name: Реестр платежей
      path: incoming_requests_path
  agent:
    - name: Все платежи
      path: payments_path
    - name: Запросы баланса
      path: balance_requests_path
    - name: Оборот
      path: turnover_stats_path
  working_group:
    - name: Все платежи
      path: payments_path
    - name: Запросы баланса
      path: balance_requests_path
    - name: Статистика
      path: dashboard_path
  ppay:
    - name: Запросы баланса
      path: balance_requests_path
