basic_auth:
  username: ppay
  password: password
ppay_commission: 4
national_currencies:
  - RUB
  - UZS
  - TJS
  - IDR
  - KZT
  - UAH
  - TRY
  - KGS
payment_systems:
  - Sberbank
  - Tinkoff
  - Raiffeisen
  - AlfaBank
  - HUMO
  - Банк ЦентрКредит
  - Halyk Bank
  - Jusan Bank
  - Kaspi Bank
  - Другой банк
  - IBAN
  - PrivatBank
  - MonoBank
  - PUMB
  - PermataBank
  - Optima24
  - Halyk
  - Bakai24
  - Demir
  - UzCard

navbar:
  admin:
    - name: Все платежи
      path: payments_path
    - name: Объявления
      path: advertisements_path
    - name: Запросы баланса
      path: balance_requests_path
  merchant:
    - name: Все платежи
      path: payments_path
    - name: Создать оплату
      path: new_payments_deposit_path
    - name: Запросы баланса
      path: balance_requests_path
  processer:
    - name: Все платежи
      path: payments_path
    - name: Объявления
      path: advertisements_path
    - name: Курсы бирж
      path: rate_snapshots_path
    - name: Запросы баланса
      path: balance_requests_path
    - name: Телеграм Бот
      path: edit_processers_profile_path
  support:
    - name: Все платежи
      path: payments_path
    - name: Объявления
      path: advertisements_path
    # - name: Курсы бирж
    #   path: rate_snapshots_path
    - name: Запросы баланса
      path: balance_requests_path
