basic_auth:
  username: ppay
  password: password
ppay_commission: 4
national_currencies:
  - RUB
  - UZS
  - TJS
  - IDR
  - KZT
payment_systems:
  - Sberbank
  - Tinkoff
  - Raiffeisen
  - AlfaBank
  - HUMO
  - Банк ЦентрКредит
  - Halyk Bank
  - Jysan Bank
  - Kaspi Bank
  - Другой банк
navbar:
  admin:
    - name: Все платежи
      path: payments_path
    - name: Объявления
      path: advertisements_path
    - name: Транзакции
      path: transactions_path
    - name: Запросы баланса
      path: balance_requests_path
  merchant:
    - name: Все платежи
      path: payments_path
    - name: Транзакции
      path: transactions_path
    - name: Запросы баланса
      path: balance_requests_path
  processer:
    - name: Все платежи
      path: payments_path
    - name: Объявления
      path: advertisements_path
    - name: Курсы бирж
      path: rate_snapshots_path
    - name: Транзакции
      path: transactions_path
    - name: Запросы баланса
      path: balance_requests_path
  support:
    - name: Все платежи
      path: payments_path
    - name: Объявления
      path: advertisements_path
    # - name: Курсы бирж
    #   path: rate_snapshots_path
    # - name: Транзакции
    #   path: transactions_path
    - name: Запросы баланса
      path: balance_requests_path
