services:

  postgres:
    image: postgres:14.5-bullseye
    restart: unless-stopped
    env_file: ./ppay_app/.env.dev
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.5-bullseye
    restart: unless-stopped
    env_file: ./ppay_app/.env.dev
    volumes:
      - redis_data:/data

  worker:
    build:
      context: ./ppay_app
      dockerfile: Dockerfile
      args:
        RAILS_ENV: development
        BUNDLE_PATH: /bundle
    depends_on:
      - app
      - postgres
      - redis
    env_file: ./ppay_app/.env.dev
    entrypoint: ./entrypoint-sidekiq.sh
    restart: unless-stopped
    volumes:
      - ./ppay_app:/app
      - ./ppay_app/config/database.yml.docker:/app/config/database.yml

  cron:
    build:
      context: ./ppay_app
      dockerfile: Dockerfile.cron
      args:
        RAILS_ENV: development
        BUNDLE_PATH: /bundle
    depends_on:
      - app
      - postgres
      - redis
      - worker
    env_file: ./ppay_app/.env.dev
    entrypoint: ./entrypoint-cron.sh
    restart: unless-stopped
    volumes:
      - ./ppay_app:/app
      - ./ppay_app/config/database.yml.docker:/app/config/database.yml

  app:
    build:
      context: ./ppay_app
      dockerfile: Dockerfile
      args:
        RAILS_ENV: development
        BUNDLE_PATH: /bundle
    depends_on:
      - postgres
      - redis
    ports:
      - 3000:3000
    env_file: ./ppay_app/.env.dev
    entrypoint: ./entrypoint-rails.sh
    volumes:
      - ./ppay_app:/app
      - ./ppay_app/config/database.yml.docker:/app/config/database.yml

volumes:
  db_data:
  redis_data:
