default: &default
  adapter: postgresql
  encoding: "unicode"
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 40 } %>
  timeout: 5000

development:
  <<: *default
  database: telegram_service_development

test:
  <<: *default
  database: telegram_service_test

production:
  <<: *default
  database: telegram_service_production

