# .rubocop.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'public/**/*'
    - 'config/**/*'
    - 'Gemfile'
    - 'lib/tasks/*'

Metrics/BlockLength:
  AllowedMethods: ['included']
  Exclude:
    - 'spec/**/*'

Lint/Void:
  Exclude:
    - 'app/models/concerns/state_machines/payments/**/*'

Metrics/ClassLength:
  Exclude:
    - 'app/models/payment.rb'

Metrics/MethodLength:
  Exclude:
    - 'spec/support/swagger/schemas/v1/**/*'

Lint/MissingSuper:
  Exclude:
    - 'app/services/payments/update_callback_service.rb'

    
Style/Documentation:
  Enabled: false
