# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem 'rails', '~> 7.0.3', '>= 7.0.3.1'

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem 'sprockets-rails'

# Use sqlite3 as the database for Active Record
# gem "sqlite3", "~> 1.4"

gem 'pg'

# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', '~> 5.0'

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem 'importmap-rails'

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem 'turbo-rails'

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem 'stimulus-rails'

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem 'jbuilder'

# Use Redis adapter to run Action Cable in production
gem 'redis', '~> 4.0'

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', require: false

# Use Sass to process CSS
# gem "sassc-rails"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

gem 'haml'

gem 'sidekiq'

# гем для запуска задач из CRON:
gem 'whenever', require: false

gem 'devise'
gem 'devise-i18n'

gem 'rswag'

gem 'config'

gem 'active_model_serializers', '~> 0.10.0'

# decorators
gem 'draper'

gem 'jsonapi-serializer'

gem 'credit_card_validations'
gem 'font-awesome-rails'
gem 'simple_form'

gem 'data_migrate'
gem 'after_commit_everywhere', '~> 1.0'
gem "audited",  "~> 5.0"
gem 'filepond-rails'
gem "rqrcode", "~> 2.0"
gem 'browser'
gem 'health_check'
gem 'memory_profiler'
gem 'stackprof'
gem 'rack-mini-profiler', require: false
gem 'telegram-bot-ruby', '~> 1.0'
gem 'interactor', '~> 3.0'
gem 'acts_as_paranoid'
gem 'acts_as_archival'
gem 'pghero'
gem 'pg_query', '>= 2'
gem 'jwt'
gem 'devise-two-factor'
gem 'inline_svg'

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails'
  gem 'ffaker'
  gem 'pry-rails'
  gem 'rspec-rails'
  gem "byebug", "~> 11.1"
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem 'web-console'

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"

  gem 'foreman'
  gem 'rubocop', require: false
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'shoulda-matchers', '~> 5.0'
  gem 'webdrivers'
  gem 'webmock'
end

gem 'aasm'
gem 'aws-sdk-s3', require: false
gem 'pagy'
gem 'pundit', '~> 2.2'
gem 'tailwindcss-rails', '~> 2.0'
gem 'caxlsx'
gem 'caxlsx_rails'
gem 'dotenv-rails', groups: [:development, :test]
