// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import BalanceRequestsController from "controllers/balance_requests_controller"
application.register("balance_requests", BalanceRequestsController)

import CountdownController from "controllers/countdown_controller"
application.register("countdown", CountdownController)

import Inputmask__CardNumberController from "controllers/inputmask/card_number_controller"
application.register("inputmask--card-number", Inputmask__CardNumberController)

import NotificationsController from "controllers/notifications_controller"
application.register("notifications", NotificationsController)

import ChartRefreshController from "./chat_refresh_controller"
application.register("chat_refresh", ChartRefreshController)

import FilepondController from "controllers/filepond_controller"
application.register("filepond", FilepondController)

import ModalController from "controllers/modal_controller"
application.register("modal", ModalController)

import ClipboardController from "controllers/clipboard_controller"
application.register("clipboard", ClipboardController)
