// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import BalanceRequestsController from "controllers/balance_requests_controller"
application.register("balance_requests", BalanceRequestsController)

import CountdownController from "controllers/countdown_controller"
application.register("countdown", CountdownController)

import Inputmask__CardNumberController from "controllers/inputmask/card_number_controller"
application.register("inputmask--card-number", Inputmask__CardNumberController)

import NotificationsController from "controllers/notifications_controller"
application.register("notifications", NotificationsController)

import ModalController from "controllers/modal_controller"
application.register("modal", ModalController)
