// This file is auto-generated by controllersbin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// controllersbin/rails generate stimulus controllerName

import { application } from "controllers/application"

import Inputmask__CardNumberController from "controllers/inputmask/card_number_controller"
application.register("inputmask--card-number", Inputmask__CardNumberController)

import PaymentsController from "controllers/payments_controller"
application.register("payments", PaymentsController)
